# These are supported funding model platforms

custom: ["https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=cedricpaille%40gmail%2ecom&lc=CY&item_name=codetronic&currency_code=EUR&bn=PP%2dDonationsBF%3abtn_donateCC_LG%2egif%3aNonHosted", "https://github.com/sponsors/Furtif"]
github: [cedricp, Furtif]
